import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';

export const scrapeJobs = sqliteTable('scrape_jobs', {
  id: text('id').primaryKey(),
  searchTerm: text('search_term').notNull(),
  language: text('language').notNull().default('es'),
  bboxJson: text('bbox_json').notNull(),
  gridCellKm: real('grid_cell_km').notNull(),
  cellCount: integer('cell_count').notNull(),
  status: text('status', { enum: ['pending', 'running', 'enriching', 'done', 'error'] }).notNull().default('pending'),
  businessesFound: integer('businesses_found').notNull().default(0),
  enrichmentProgress: integer('enrichment_progress').notNull().default(0),
  cellsDone: integer('cells_done').notNull().default(0),
  errorMessage: text('error_message'),
  createdAt: text('created_at').notNull(),
  completedAt: text('completed_at'),
});

export const businesses = sqliteTable('businesses', {
  id: text('id').primaryKey(),
  jobId: text('job_id').notNull(),
  name: text('name').notNull(),
  address: text('address'),
  phone: text('phone'),
  website: text('website'),
  hoursJson: text('hours_json'),
  rating: real('rating'),
  reviewCount: integer('review_count'),
  category: text('category'),
  latitude: real('latitude'),
  longitude: real('longitude'),
  instagram: text('instagram'),
  facebook: text('facebook'),
  twitter: text('twitter'),
  tiktok: text('tiktok'),
  linkedin: text('linkedin'),
  youtube: text('youtube'),
  emailsJson: text('emails_json'),
  socialEnriched: integer('social_enriched').notNull().default(0),
  scrapedAt: text('scraped_at').notNull(),
  outreachStatus: text('outreach_status'),
  outreachNote: text('outreach_note'),
  locCountry: text('loc_country'),
  locState: text('loc_state'),
  locCity: text('loc_city'),
  locNeighbourhood: text('loc_neighbourhood'),
  locationEnriched: integer('location_enriched').notNull().default(0),
});
