import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';

export const scrapeJobs = sqliteTable('scrape_jobs', {
  id: text('id').primaryKey(),
  searchTerm: text('search_term').notNull(),
  language: text('language').notNull().default('es'),
  bboxJson: text('bbox_json').notNull(),
  gridCellKm: real('grid_cell_km').notNull(),
  cellCount: integer('cell_count').notNull(),
  status: text('status', { enum: ['pending', 'running', 'enriching', 'done', 'error'] }).notNull().default('pending'),
  businessesFound: integer('businesses_found').notNull().default(0),
  enrichmentProgress: integer('enrichment_progress').notNull().default(0),
  cellsDone: integer('cells_done').notNull().default(0),
  // Persisted for boot-time resume of interrupted jobs; NULL on legacy rows (not resumable)
  geometryJson: text('geometry_json'),
  extractEmails: integer('extract_emails').notNull().default(1),
  errorMessage: text('error_message'),
  createdAt: text('created_at').notNull(),
  completedAt: text('completed_at'),
});

export const businesses = sqliteTable('businesses', {
  id: text('id').primaryKey(),
  jobId: text('job_id').notNull(),
  name: text('name').notNull(),
  address: text('address'),
  phone: text('phone'),
  website: text('website'),
  hoursJson: text('hours_json'),
  rating: real('rating'),
  reviewCount: integer('review_count'),
  category: text('category'),
  latitude: real('latitude'),
  longitude: real('longitude'),
  instagram: text('instagram'),
  facebook: text('facebook'),
  twitter: text('twitter'),
  tiktok: text('tiktok'),
  linkedin: text('linkedin'),
  youtube: text('youtube'),
  emailsJson: text('emails_json'),
  socialEnriched: integer('social_enriched').notNull().default(0),
  scrapedAt: text('scraped_at').notNull(),
  outreachStatus: text('outreach_status'),
  outreachNote: text('outreach_note'),
  locCountry: text('loc_country'),
  locState: text('loc_state'),
  locCity: text('loc_city'),
  locNeighbourhood: text('loc_neighbourhood'),
  locationEnriched: integer('location_enriched').notNull().default(0),
  followUpStatus: text('follow_up_status'),
  repliedAt: text('replied_at'),
  replyType: text('reply_type', { enum: ['auto', 'real', 'unknown'] }),
});

export const premiumAnalyses = sqliteTable('premium_analyses', {
  id: text('id').primaryKey(),
  businessId: text('business_id').notNull(),
  status: text('status', { enum: ['pending', 'running', 'done', 'failed'] }).notNull().default('pending'),
  renderOutcome: text('render_outcome'),
  finalUrl: text('final_url'),
  signalsJson: text('signals_json'),
  cookieWall: integer('cookie_wall').notNull().default(0),
  consoleErrorsJson: text('console_errors_json'),
  desktopScreenshotPath: text('desktop_screenshot_path'),
  mobileScreenshotPath: text('mobile_screenshot_path'),
  htmlPath: text('html_path'),
  networkLogPath: text('network_log_path'),
  detectedSigsJson: text('detected_sigs_json'),
  errorMessage: text('error_message'),
  createdAt: text('created_at').notNull(),
  completedAt: text('completed_at'),
});
